name: Preview deployment workflow

on:
    push:
        branches-ignore:
            - master

jobs:
    prisma_migrate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install Prisma
              run: npm install prisma -D
            - name: Deploy migrations
              env:
                  DATABASE_URL: ${{ secrets.PREVIEW_DATABASE_URL }}
              run: npx prisma migrate reset --force
